version: "2"
services:

  glue_compile:
    build: .
    volumes:
      - ./src:/opt/code
      - ./dist:/opt/dist
    container_name: glue_node

  web:
    image: nginx:1.14.0-alpine
    volumes:
      - ".:/usr/share/nginx/html:ro"
    ports:
      - "172.17.0.1:7000:80"
    container_name: glue_nginx

  python:
    build: ./docker/build/python/.
    container_name: glue_python
    links:
      - selenium
    volumes:
      - ".:/opt/code:ro"
    environment:
      REMOTE_SELENIUM: selenium
      WEB_HOST: http://172.17.0.1:7000

  selenium:
    image: selenium/standalone-firefox-debug:2.53.1
    container_name: glue_firefox
